1 feature am
Delegant/PadawansTelegramBot pull request #1
Opened 2022-06-19 21:14 UTC by algmironov

Созданы модели User, Report, ReportsPicture 
Созданы репозитории USERS, REPORTS, PICTURES
Созданы таблицы users, reports, pictures
Подключен liquibase + migrations

(application.properties не включен в коммит, тем не менее необходимые изменения имеются в aplication-team.properties , касающиеся БД и liquibase)

2022-06-19 21:44 UTC, algmironov commented
отдельным коммитом добавил геттеры, сеттеры и конструкторы (рукалицо, забыл)

2022-06-20 21:21 UTC, Delegant requested changes
посмотрел, все отлично, но без назначения владельца таблицам не работает. 
liquibase вообще никак не стартует.

2022-06-20 21:21 UTC, Delegant commented on target/classes/liquibase/scripts/migrations.sql
> +
alter table users
    owner to "username";

2022-06-20 21:21 UTC, Delegant commented on target/classes/liquibase/scripts/migrations.sql
> +
alter table reports
owner to "username";

2022-06-20 21:21 UTC, Delegant commented on target/classes/liquibase/scripts/migrations.sql
> +);
alter table pictures
owner to "username";

2022-06-21 17:07 UTC, Delegant approved these changes
Все ок

2022-06-21 17:08 UTC, merged