PR второго этапа.
Delegant/PadawansTelegramBot pull request #5
Opened 2022-06-24 20:48 UTC by algmironov

2022-06-25 17:35 UTC, OlgaLugacheva requested changes

2022-06-25 17:35 UTC, OlgaLugacheva commented on src/main/java/pro/sky/telegrambot/repository/UserRepository.java
> +    User findUserById(Long id);
зачем это вообще если есть метод в родителе finById ? 
давайте уберем, мне кажется, не нужен

2022-06-25 17:35 UTC, OlgaLugacheva commented on src/main/java/pro/sky/telegrambot/repository/ReportsRepository.java
> +    Collection<Report> findAllByUserId(Long userId);
а точно? 
а точно не `Collection<Report> findAllByUser(Long userId);` ?

2022-06-27 06:10 UTC, Delegant approved these changes
по мне все хорошо, комментарии добавил, исключительно как свое мнение и для обратной связи, на истинность не претендую.
Так же, думаю файлы фоток карты лучше добавить в гитигнор.

2022-06-27 06:10 UTC, Delegant commented on src/main/java/pro/sky/telegrambot/listener/TelegramBotUpdatesListener.java
> +    private boolean hasCallbackQuery(Update update) {
мне кажется можно было проще написать

2022-06-27 06:10 UTC, Delegant commented on src/main/java/pro/sky/telegrambot/listener/TelegramBotUpdatesListener.java
> +            case (ABOUT_US_CASE):
в кейсах много повторяющегося кода. Думаю можно сократить.

2022-06-27 06:10 UTC, Delegant commented on src/main/java/pro/sky/telegrambot/controller/ReportController.java
> +            savedCollection = reportService.savePictures(reportId, files);
возможно, лучше перенести обработку ошибки в сервис?

2022-06-27 16:52 UTC, Kulachenkov approved these changes

2022-06-30 22:13 UTC, merged